name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build, Test, and SCA Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Make sure your requirements.txt pins compatible versions.
          pip install -r requirements.txt

      - name: Run tests with pytest
        env:
          # Ensures Python looks in the repository root for modules (like app.py)
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pip install pytest
          pytest

      - name: Run SCA check with Safety
        run: |
          pip install safety
          # Use the new 'safety scan' command with no interactive input.
          # The --exit-code 0 flag prevents the job from failing if vulnerabilities are found.
          safety scan --exit-code 0 --no-input
        # Optionally, if you have a SAFETY_API_KEY stored in your repository secrets,
        # uncomment the env: block below to use it.
        # env:
        #   SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}

  codeql-analysis:
    name: CodeQL Analysis (SAST)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        language: [ 'python' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dast-scan:
    name: DAST Scan with OWASP ZAP
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python for app launch
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for DAST
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start the Flask app in the background
        run: |
          nohup python app.py > app.log 2>&1 &
          # Wait up to 30 seconds for the app to start.
          for i in {1..10}; do
            if curl -s http://localhost:5000/ > /dev/null; then
              echo "Flask app is ready."
              exit 0
            fi
            echo "Waiting for Flask app to start..."
            sleep 3
          done
          echo "Flask app did not start in time."
          exit 1

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://localhost:5000'
